global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "api"
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["api"]
        type: "A"
        port: 8080

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
